### PR TITLE
Add licensezero script invoking l0- as subcommands

### PR DESCRIPTION
**Pull request by kemitchell**
@zkat: Will this do the trick for npx?

Basically, licensezero is a lot of bin scripts, all prefixed with `l0-`. This PR adds a bin script with the same name as the package, `licensezero`, that "proxies" to those subcommands. I think I'll also add an alias as `l0`.

If there were some way to tell npx, "hey, if you go looking for a l0- command, it's actually from the licensezero package", that would be preferable.  But that sounds like another registry ... of script names to package names.  Registries are a lot of work, I hear.

### CODE REVIEW

**Comment by zkat** [comment]
Using this through git confuses npx a bit due to its automagic binary guessing whenever there's multiple binaries (because the name of this repo is `licensezero-cli`, not `licensezero`, but the registry version -should- work just fine once published to the registry. You could also add a `licensezero-cli` alias for the main one to get that to work.

Other than that, lgtm. Thanks! :D

**Comment by kemitchell** [comment]
Hey @zkat, what'd you mean by?:

> You could also add a `licensezero-cli` alias for the main one to get that to work.

**Comment by zkat** [comment]
```
"bin": {
  "licensezero": "./bin-loader",
  "licensezero-bin": "./bin-loader",
  ....
}
```

npx checks for a binary with the same name as the package first, then it just... picks one at random. See https://github.com/zkat/npx/blob/latest/index.js#L89-L91

**Comment by kemitchell** [comment]
I believe I've got this in bd29bd539b173a59666ed4d173db98752750c5ba

**Pull request closed without merging**
